#!/bin/sh


##
## /usr/lib/live/config/5010-user-change-password
##


##
## ## Load Lib
##

. /lib/live/config.sh


##
## live-config(7) - System Configuration Components
##

##
## > Refer: [/usr/lib/live/config/0030-user-setup](https://salsa.debian.org/live-team/live-config/-/blob/master/components/0030-user-setup?ref_type=heads)
##


#set -e

Init () {

	##
	## ## Checking if package is installed
	##

	if ! pkg_is_installed "passwd" || \
		component_was_executed "passwd"
	then
		exit 0
	fi

	echo -n " passwd"
}

Config () {

	##
	## ## change user password
	##
	## > echo 'username:password' | chpasswd
	##

	echo 'lika:lika' | chpasswd


	##
	## ## remove user password
	##

	#passwd -d lika


	##
	## ## Creating state file
	##

	touch /var/lib/live/config/user-change-password

}

Init
Config
